apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: web
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      volumes:
      - name: vol
        configMap:
          name: web-cm
      containers:
      - image: nginx:alpine
        name: nginx
        volumeMounts:
        - name: vol
          mountPath: /usr/share/nginx/html/
        resources: {}
status: {}
