apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-svc
  namespace: jenkins
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  - name: server
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30080
  selector:
    app: jenkins
status:
  loadBalancer: {}
